//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.Connections.AtiranAccModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AccModelEntities : DbContext
    {
        public AccModelEntities()
            : base("name=AccModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<SubSystem> SubSystems { get; set; }
        public virtual DbSet<SubSystemPermission> SubSystemPermissions { get; set; }
        public virtual DbSet<UserFieldPermission> UserFieldPermissions { get; set; }
        public virtual DbSet<UserFormPermission> UserFormPermissions { get; set; }
        public virtual DbSet<UserPersonalizationForColor> UserPersonalizationForColors { get; set; }
        public virtual DbSet<UserPersonalizationForFont> UserPersonalizationForFonts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ShortcutKey> ShortcutKeys { get; set; }
    
        public virtual int RestoreToDefault(Nullable<bool> deleteUsers)
        {
            var deleteUsersParameter = deleteUsers.HasValue ?
                new ObjectParameter("deleteUsers", deleteUsers) :
                new ObjectParameter("deleteUsers", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestoreToDefault", deleteUsersParameter);
        }
    
        public virtual int AddUser(Nullable<int> userID, string dBname)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var dBnameParameter = dBname != null ?
                new ObjectParameter("DBname", dBname) :
                new ObjectParameter("DBname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", userIDParameter, dBnameParameter);
        }
    }
}
