//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.Connections.AtiranAccModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortcutKey
    {
        public int ID { get; set; }
        public string Shurtcut { get; set; }
        public string MainForm { get; set; }
        public string Dis { get; set; }
        public string EnumName { get; set; }
    }
}
