//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.Connections.AtiranAccModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserFieldPermissions = new HashSet<UserFieldPermission>();
            this.UserFormPermissions = new HashSet<UserFormPermission>();
            this.SubSystemPermissions = new HashSet<SubSystemPermission>();
            this.UserPersonalizationForColors = new HashSet<UserPersonalizationForColor>();
            this.UserPersonalizationForFonts = new HashSet<UserPersonalizationForFont>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public byte[] UserPassWord { get; set; }
        public Nullable<bool> Active { get; set; }
        public string BackGroundAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFieldPermission> UserFieldPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFormPermission> UserFormPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSystemPermission> SubSystemPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPersonalizationForColor> UserPersonalizationForColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPersonalizationForFont> UserPersonalizationForFonts { get; set; }
    }
}
