//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.Connections.AtiranAccModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPersonalizationForColor
    {
        public int PersonalizationColorID { get; set; }
        public int UserID { get; set; }
        public int ControlNameID { get; set; }
        public int ControlColorID { get; set; }
        public int R { get; set; }
        public int G { get; set; }
        public int B { get; set; }
    
        public virtual User User { get; set; }
    }
}
