//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.Connections.AtiranAccModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFormPermission
    {
        public int UserFormPermissionID { get; set; }
        public int UserID { get; set; }
        public int FormID { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual User User { get; set; }
    }
}
